import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class TranslateService {
  private translations: any = {
    en: {
      HOME: 'Home',
      COMPANIES: 'Companies',
      ABOUT: 'About',
      CONTACT: 'Contact',
      SIGN_IN: 'Sign In',
      LANGUAGE: 'Language',
      WELCOME: 'Welcome to Rentmo',
      DESCRIPTION: 'Find the best car rental companies worldwide.',
      LOGIN_TYPE_PROMPT: 'Select your login type:',
      ADMIN: 'Admin',
      COMPANY: 'Company',
      SELECT_COMPANY: 'Select Rental Company',
      CARS: 'Cars',
      RENTALS: 'Rentals',
      COMPANY_EMPLOYEES: 'Employees',
      COLUMN_MODEL: 'Model',
      COLUMN_BRAND: 'Brand',
      COLUMN_ACTIONS: 'Actions',
      ADD_CAR: 'Add Car',
      DELETE_CONFIRMATION: 'Are you sure you want to delete this car?',
      EDIT_CAR: 'Edit Car',
      SAVE: 'Save',
      CANCEL: 'Cancel',
      SEARCH_PLACEHOLDER: 'Search by brand or model',
      ALL_BRANDS: 'All Brands',
      ENGINE: 'Engine',
      PERFORMANCE: 'Performance',
      TURBO: 'Turbo',
      SEATS: 'Seats',
      PREVIOUS: 'Previous',
      NEXT: 'Next',
      NO_CARS_FOUND: 'There are no cars.',
      BRAND: 'Brand',
      MODEL: 'Model',
      CAR_LIST_TITLE: 'Car List',
      DELETE: 'Delete',
      CONFIRM_DELETE_MESSAGE: 'Are you sure you want to remove this car?',
      ERROR_LOADING_DATA: 'Error loading data. Please try again later.',
      ERROR_DELETING_CAR: 'Error deleting the car. Please try again later.',
      ERROR_OCCURRED: 'An error occurred',
      RENTALS_LIST: 'Rentals List',
      START_DATE: 'Start Date',
      END_DATE: 'End Date',
      PRICE: 'Price',
      NO_RENTALS: 'There is no rental.',
      CONFIRM_COMPANY_DELETE: 'Are you sure you want to delete the company',
      LOCATED: 'Located at',
      CLOSE: 'Close',
      COMPANY_NAME: 'Name',
      COMPANY_LOCATION: 'Location',
      COMPANY_PHONE_NUMBER: 'Phone Number',
      COMPANY_ACTIONS: 'Actions',
      ADD_COMPANY: 'Add new company',
      DELETE_CONFIRM: 'Confirm Deletion',
      CHECK_OFFER: 'Check Offer',
      ADD: 'Add',
      LOGIN_AS: 'Login as',
      USER_ID: 'Enter your user ID',
      LOGOUT: 'Logout',
      EMAIL: 'Email',
      SIGN_UP: 'Sign Up',
      PASSWORD: 'Password',
      CONFIRM_PASSWORD: 'Confirm password',
      ALREADY_HAVE_ACCOUNT: 'Already have an account',
      DONT_HAVE_ACCOUNT: 'Do not have account',
      SIGN_IN_TITTLE: 'Sign In',
      SIGN_UP_TITTLE: 'Sign Up',
      LAST_NAME:'Last name',
      FIRST_NAME:'First name'
    },
    pl: {
      HOME: 'Strona główna',
      COMPANIES: 'Firmy',
      ABOUT: 'O nas',
      CONTACT: 'Kontakt',
      SIGN_IN: 'Zaloguj się',
      LANGUAGE: 'Język',
      WELCOME: 'Witamy w Rentmo',
      DESCRIPTION: 'Znajdź najlepsze wypożyczalnie samochodów na świecie.',
      LOGIN_TYPE_PROMPT: 'Wybierz rodzaj logowania:',
      ADMIN: 'Administrator',
      COMPANY: 'Firma',
      SELECT_COMPANY: 'Wybierz firmę wynajmu',
      CARS: 'Samochody',
      RENTALS: 'Wynajmy',
      COMPANY_EMPLOYEES:'Pracownicy',
      COLUMN_MODEL: 'Model',
      COLUMN_BRAND: 'Marka',
      COLUMN_ACTIONS: 'Akcje',
      ADD_CAR: 'Dodaj samochód',
      DELETE_CONFIRMATION: 'Czy na pewno chcesz usunąć ten samochód?',
      EDIT_CAR: 'Edytuj samochód',
      SAVE: 'Zapisz',
      CANCEL: 'Anuluj',
      SEARCH_PLACEHOLDER: 'Szukaj według marki lub modelu',
      ALL_BRANDS: 'Wszystkie Marki',
      ENGINE: 'Silnik',
      PERFORMANCE: 'Osiągi',
      TURBO: 'Turbo',
      SEATS: 'Miejsca',
      PREVIOUS: 'Poprzednia',
      NEXT: 'Następna',
      NO_CARS_FOUND: 'Brak samochodów.',
      BRAND: 'Marka',
      MODEL: 'Model',
      CAR_LIST_TITLE: ' Lista Samochodów',
      DELETE: 'Usuń',
      CONFIRM_DELETE_MESSAGE: 'Jesteś pewien, że chcesz usunąć ten samochód?',
      ERROR_LOADING_DATA: 'Błąd podczas ładowania danych. Spróbuj ponownie później.',
      ERROR_DELETING_CAR: 'Błąd podczas usuwania samochodu. Spróbuj ponownie później.',
      ERROR_OCCURRED: 'Wystąpił błąd',
      RENTALS_LIST: 'Lista Wynajmów',
      START_DATE: 'Data rozpoczęcia',
      END_DATE: 'Data zakończenia',
      PRICE: 'Cena',
      NO_RENTALS: 'Brak wynajmów.',
      CONFIRM_COMPANY_DELETE: 'Czy na pewno chcesz usunąć firmę',
      LOCATED: 'Zlokalizowaną w/we ',
      CLOSE: 'Zamknij',
      COMPANY_NAME: 'Nazwa',
      COMPANY_LOCATION: 'Lokalizacja',
      COMPANY_PHONE_NUMBER: 'Numer Telefonu',
      COMPANY_ACTIONS: 'Akcje',
      ADD_COMPANY: 'Dodaj nową wypożyczalnie',
      DELETE_CONFIRM: 'Potwierdzenie usuwania',
      CHECK_OFFER: 'Sprawdź oferte',
      ADD: 'Dodaj',
      LOGIN_AS: 'Zalogowano jako',
      USER_ID: 'Podaj ID użytkownika',
      LOGOUT: 'Wyloguj się',
      EMAIL: 'Email',
      SIGN_UP: 'Zarejestruj',
      PASSWORD: 'Hasło',
      CONFIRM_PASSWORD: 'Potwierdź hasło',
      ALREADY_HAVE_ACCOUNT: 'Mam już konto',
      DONT_HAVE_ACCOUNT: 'Nie mam konta',
      SIGN_IN_TITTLE: 'Logowanie',
      SIGN_UP_TITTLE: 'Rejestracja',
      LAST_NAME: 'Nazwisko',
      FIRST_NAME: 'Imię'
    },
  };

  private currentLang: string = 'en';

  setLanguage(lang: string) {
    this.currentLang = lang;
  }

  translate(key: string): string {
    return this.translations[this.currentLang]?.[key] || key;
  }

  getCurrentLanguage(): string {
    return this.currentLang;
  }
}
